### ISSUE TITLE
Feature request: Availability on pypi.org (to use vppopt as a containerized service)

### ISSUE THREAD

**Issue by Aiscargeauh** [cenaero-enb/h2cs-design#11]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Feature request: porting the tool to Pypi.org, allowing external developers to easily use it on a dockerized environment.

* **What is the current behavior?**
Having to create the environment in order to install + run the tool.
Having to create an error prone .dockerfile to use the tool as a service.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**
Use `pip install vppopt` to install and use the tool.

* **What is the motivation / use case for changing the behavior?**
We are trying to use the tool as a service, containerizing the project to use it with an external HMI.
Currently, all the steps noted in README.md have to be ported to a .dockerfile file, which is error prone and not stable. It could be replaced by one single line (`pip install vppopt`).

* **Please tell us about your environment:**
  
  - VPPopt Version: v2021.01
  - Operating System: [~~Windows~~ | ~~Linux~~ | Docker WSL2]
  - Python version: 3.9

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
We discussed about this possible feature un a meeting, contact nicolas.ruhland@external.engie.com for more information.

**Comment by Aiscargeauh** [comment]
Hi

As information for anyone interested in the feature, here is a workaround I am using the following dockerfile:

```
FROM python:3.8-slim-buster

WORKDIR /h2cs-design
COPY ./h2cs-design .

RUN ["python3", "setup.py", "install"]
RUN ["pip3", "install", "-r",  "requirements.txt"]
RUN ["apt", "update"]
RUN ["apt", "install", "coinor-cbc", "-y"]
RUN ["vppopt", "init", "-pdir", "Project"]
EXPOSE 4000
ENTRYPOINT ["python", "app.py"]
```

and added an app.py in the project root folder:

```python
from flask import Flask
from flask_executor import Executor
from flask_executor.futures import Future
from flask_shell2http import Shell2HTTP

app = Flask(__name__)
executor = Executor(app)
shell2http = Shell2HTTP(app=app, executor=executor)

def my_callback_fn(extra_callback_context, future: Future):
    """
    Will be invoked on every process completion
    """
    print("[i] Process running ?:", future.running(), flush=True)
    print("[i] Process completed ?:", future.done(), flush=True)
    print("[+] Result: ", future.result(), flush=True)
    # future.result() returns a dictionary
    print("[+] Context: ", extra_callback_context, flush=True)


shell2http.register_command(endpoint="help", command_name="vppopt --help", callback_fn=my_callback_fn)
shell2http.register_command(endpoint="version", command_name="vppopt --version", callback_fn=my_callback_fn)

shell2http.register_command(endpoint="initialize", command_name="vppopt init -pdir Project", callback_fn=my_callback_fn)
shell2http.register_command(endpoint="run", command_name="vppopt run -wf /h2cs-design/Project/vppopt.json", callback_fn=my_callback_fn)


if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=4000)
```

It's using [flask_shell2http](https://github.com/Eshaan7/Flask-Shell2HTTP) to create an api for the cli tool.

**Comment by Aiscargeauh** [comment]
It is running on a private server for now, but my goal is to develop a small human interface allowing the user to interact with `vppopt` so I will keep you updated on the subject :)
The feature request would still be nice to have, I'm letting the issue opened for now.

**Comment by longlevan** [comment]
Yeah, no problem. I am trying to establish CI/CD pipeline with github actions. Once this will be established python package will be automatically published on PyPI everytime when there is new release.

**Comment by longlevan** [comment]
A new version has been published on pypi: https://pypi.org/project/vppopt/. @Aiscargeauh: Please check if this work for you. All dependencies would be automatically installed when you run `pip install vppopt`. Please let me know if there will be a problem. Otherwise, feel free to close this issue. Thanks!

**Comment by Aiscargeauh** [comment]
Awesome! I have been able to change my .dockerfile to add that `pip install vppopt` and it worked perfectly. Thanks for the update, closing the issue.
